In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('covid1.csv')

In [3]:
data

,State/UTs,Total Cases,Active,Discharged,Deaths,Active Ratio,Discharge Ratio,Death Ratio
0,Andaman and Nicobar,7641,9,7503,129,0.12,98.19,1.69
1,Andhra Pradesh,2059708,6453,2038960,14295,0.31,98.99,0.69
2,Arunachal Pradesh,54964,183,54501,280,0.33,99.16,0.51
3,Assam,605944,3458,596547,5939,0.57,98.45,0.98
4,Bihar,726021,46,716314,9661,0.01,98.66,1.33
5,Chandigarh,65297,30,64447,820,0.05,98.70,1.26
6,Chhattisgarh,1005624,197,991857,13570,0.02,98.63,1.35
7,Dadra and Nagar Haveli and Daman and Diu,10675,3,10668,4,0.03,99.93,0.04
8,Delhi,1439337,327,1413921,25089,0.02,98.23,1.74
9,Goa,177410,648,173423,3339,0.37,97.75,1.88
10,Gujarat,826258,212,815960,10086,0.03,98.75,1.22
11,Haryana,771049,116,760884,10049,0.02,98.68,1.30
12,Himachal Pradesh,221203,1361,216125,3717,0.62,97.70,1.68
13,Jammu and Kashmir,330885,895,325564,4426,0.27,98.39,1.34
14,Jharkhand,348415,130,343150,5135,0.04,98.49,1.47
15,Karnataka,2982869,9700,2935238,37931,0.33,98.40,1.27
16,Kerala,4838811,95349,4716728,26734,1.97,97.48,0.55
17,Ladakh,20871,42,20621,208,0.20,98.80,1.00
18,Lakshadweep,10365,1,10313,51,0.01,99.50,0.49
19,Madhya Pradesh,792675,106,782046,10523,0.01,98.66,1.33
20,Maharashtra,6588429,33379,6415316,139734,0.51,97.37,2.12
21,Manipur,122545,1444,119208,1893,1.18,97.28,1.54
22,Meghalaya,82815,893,80490,1432,1.08,97.19,1.73
23,Mizoram,111651,13316,97955,380,11.93,87.73,0.34
24,Nagaland,31547,228,30645,674,0.72,97.14,2.14
25,Odisha,1034276,4817,1021180,8279,0.47,98.73,0.80
26,Puducherry,127296,611,124836,1849,0.48,98.07,1.45
27,Punjab,601992,228,585224,16540,0.04,97.21,2.75
28,Rajasthan,954383,40,945389,8954,0.00,99.06,0.94
29,Sikkim,31739,189,31159,391,0.60,98.17,1.23
30,Tamil Nadu,2684641,15238,2633534,35869,0.57,98.10,1.34
31,Telengana,668722,4056,660730,3936,0.61,98.80,0.59
32,Tripura,84299,102,83381,816,0.12,98.91,0.97
33,Uttar Pradesh,1710014,133,1686984,22897,0.01,98.65,1.34
34,Uttarakhand,343739,179,336163,7397,0.05,97.80,2.15
35,West Bengal,1579463,7513,1552997,18953,0.48,98.32,1.20